# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      seahalee.github.io
url:              http://hyde.getpoole.com
baseurl:          https://hyde.getpoole.com/

author:
  name:           seahalee
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:           seahalee/seahalee.github.io
  repo:           https://github.com/poole/hyde
